#include <TGraphErrors.h>
#include <TCanvas.h>
#include <TStyle.h>
#include <TAxis.h>
#include <TH2D.h>
#include <TH1D.h>
#include <TF1.h>
#include <TLegend.h>
#include <TFitResultPtr.h>
#include <TFitResult.h>
#include <TROOT.h>
#include "CC_FONLL.h"
#include "RAA.h"
#include "dnchdeta.h"
#include <iostream>
#include <fstream>
using namespace std;

/**
*   Get Nch results from file generated by PlotNchDistribution() and evaluated the integrated number of Nch for a given rapidity range
*/

//Input file should have the format :
//
// 2.50-2.75 1750 49
// 2.75-3.00 1706 41


// Intervals to integrated fit functions
int ny =7;
Double_t y[7]        ={2.5,2.75,3.0,3.25,3.50,3.75,4};


TH1* GetNchFromFile(const char* filename);
TH1* GetWeightedMeanHisto_cent(TH1* h1,TH1* h2,TH1* h3);
TH1* ProjectWeightedMeanHisto_cent(int ybin,int nbin,TH1* h_cent[10]);
void EvalNch(TH1* h_y276TeV[6]);

//______________________________________________
void EvalIntegratedNch()
{

	//---------------------------------------------------
	// Read extern file and extract values
	//---------------------------------------------------

	//Prepare histo
	TH1* h_gauss5TeV[10];
	TH1* h_pol25TeV[10];
	TH1* h_pol45TeV[10];

	TH1* h_gauss276TeV[4];
	TH1* h_pol2276TeV[4];
	TH1* h_pol4276TeV[4];

	// Get value from extern file
	for (int i = 0; i < 10; i++) {
		h_gauss5TeV[i] = GetNchFromFile(Form("gauss_5TeV/cent_%0.f_%0.f.txt",Centrality_bin[i],Centrality_bin[i+1]));
		h_pol25TeV[i] = GetNchFromFile(Form("pol2_5TeV/cent_%0.f_%0.f.txt",Centrality_bin[i],Centrality_bin[i+1]));
		h_pol45TeV[i] = GetNchFromFile(Form("pol4_5TeV/cent_%0.f_%0.f.txt",Centrality_bin[i],Centrality_bin[i+1]));
	}

	for (int i = 0; i < 4; i++) {
		h_gauss276TeV[i] = GetNchFromFile(Form("gauss_276TeV/cent_%0.f_%0.f.txt",Centrality_bin[i],Centrality_bin[i+1]));
		h_pol2276TeV[i] = GetNchFromFile(Form("pol2_276TeV/cent_%0.f_%0.f.txt",Centrality_bin[i],Centrality_bin[i+1]));
		h_pol4276TeV[i] = GetNchFromFile(Form("pol4_276TeV/cent_%0.f_%0.f.txt",Centrality_bin[i],Centrality_bin[i+1]));
	}

	// Create TH1 with the weighted mean from each tests for each value
	TH1* h_cent5TeV[10];
	TH1* h_cent276TeV[4];


	for (int i = 0; i < 10; i++) {
		h_cent5TeV[i] = GetWeightedMeanHisto_cent(h_gauss5TeV[i],h_pol25TeV[i],h_pol45TeV[i]);
		h_cent5TeV[i]->SetName(Form("cent_%0.f_%0.f",Centrality_bin[i],Centrality_bin[i+1]));
		h_cent5TeV[i]->SetTitle(Form("cent_%0.f_%0.f",Centrality_bin[i],Centrality_bin[i+1]));

	}

	for (int i = 0; i < 4; i++) {
		h_cent276TeV[i] = GetWeightedMeanHisto_cent(h_gauss276TeV[i],h_pol2276TeV[i],h_pol4276TeV[i]);
		h_cent276TeV[i]->SetName(Form("cent_%0.f_%0.f",Centrality_bin[i],Centrality_bin[i+1]));
		h_cent276TeV[i]->SetTitle(Form("cent_%0.f_%0.f",Centrality_bin[i],Centrality_bin[i+1]));

	}


	// Project h_cent5TeV on rapidity
	TF1 *fitfunction[6];
	for (size_t i = 0; i < 6; i++) {
		fitfunction[i] = new TF1("f2", "[0]*exp(-[1]*x+[2])",0, 110);
		// fitfunction[i] = new TF1("f2", "pol4",0, 110);
		fitfunction[i]->SetLineColor(2);
		// fitfunction[i]->SetParameters(2);
		fitfunction[i]->SetLineWidth(1);
		fitfunction[i]->SetLineStyle(2);
	}

	TH1* h_y5TeV[6];
	TH1* h_y276TeV[6];

	TCanvas *c0 = new TCanvas("c0","c0",20,20,800,800);
	c0->Divide(2,1);
	c0->cd(1);

	// Config. Legend
	TLegend*leg0 = new TLegend(0.12,0.55,.4,.8,NULL,"brNDC");
	leg0->SetBorderSize(0);
	leg0->SetFillColor(10);
	leg0->SetFillStyle(1);
	leg0->SetLineStyle(0);
	leg0->SetLineColor(0);
	leg0->SetTextSize(0.03);


	for (int i = 0; i < h_cent5TeV[0]->GetXaxis()->GetNbins(); i++) {
		h_y5TeV[i] = ProjectWeightedMeanHisto_cent(i,10,h_cent5TeV);
		h_y5TeV[i]->SetName(Form("y_%0.2f_%0.2f",y[i],y[i+1]));
		h_y5TeV[i]->SetTitle(Form("Nch vs centrality"));
		h_y5TeV[i]->GetYaxis()->SetTitle("dNch/d#it{y}");
		h_y5TeV[i]->GetYaxis()->SetRangeUser(0,2000);
		h_y5TeV[i]->GetXaxis()->SetTitle("cent");
		h_y5TeV[i]->SetMarkerStyle(20);
		h_y5TeV[i]->SetMarkerColor(i+1);
		h_y5TeV[i]->SetLineColor(i+1);
		h_y5TeV[i]->SetMarkerSize(0.5);

		// h_y5TeV[i]->Fit(fitfunction[i],"0QSER","",0,30);

		double nchexp 	=0.;
		double dnchexp 	=0.;
		// nchexp 					= fitfunction[i]->Integral(0,30);
		// dnchexp 				= fitfunction[i]->IntegralError(0,30);

		// printf(" ---> exp (fit)   : %.0f +/- %.0f \n",nchexp,dnchexp);

		if(i==0) h_y5TeV[i]->Draw();
		else 		 h_y5TeV[i]->Draw("same");
		fitfunction[i]->DrawCopy("same");


		leg0->AddEntry(h_y5TeV[i],Form("rapidity %.2f-%.2f",y[i],y[i+1]),"PE");

	}

	leg0->Draw("same");

	c0->cd(2);

	// Config. Legend
	TLegend*leg1 = new TLegend(0.12,0.55,.4,.8,NULL,"brNDC");
	leg1->SetBorderSize(0);
	leg1->SetFillColor(10);
	leg1->SetFillStyle(1);
	leg1->SetLineStyle(0);
	leg1->SetLineColor(0);
	leg1->SetTextSize(0.03);

	printf("\n");

	for (int i = 0; i < h_cent276TeV[0]->GetXaxis()->GetNbins(); i++) {
		h_y276TeV[i] = ProjectWeightedMeanHisto_cent(i,4,h_cent276TeV);
		h_y276TeV[i]->SetName(Form("y_%0.2f_%0.2f",y[i],y[i+1]));
		h_y276TeV[i]->SetTitle(Form("Nch vs centrality"));
		h_y276TeV[i]->GetYaxis()->SetTitle("dNch/d#it{y}");
		h_y276TeV[i]->GetYaxis()->SetRangeUser(0,2000);
		h_y276TeV[i]->GetXaxis()->SetTitle("cent");
		h_y276TeV[i]->SetMarkerStyle(20);
		h_y276TeV[i]->SetMarkerColor(i+1);
		h_y276TeV[i]->SetLineColor(i+1);
		h_y276TeV[i]->SetMarkerSize(0.5);

		leg1->AddEntry(h_y276TeV[i],Form("rapidity %.2f-%.2f",y[i],y[i+1]),"PE");

		// h_y276TeV[i]->Fit(fitfunction[i],"0QSER","",0,30);

		double nchexp 	=0.;
		double dnchexp 	=0.;
		// nchexp 					= fitfunction[i]->Integral(0,30);
		// dnchexp 				= fitfunction[i]->IntegralError(0,30);

		if(i==0)h_y276TeV[i]->Draw();
		else 		h_y276TeV[i]->Draw("same");
		fitfunction[i]->DrawCopy("same");

		// printf(" -------- Nch for %.2f < y < %.2f : \n",y[i],y[i+1]);
		// printf(" ---> exp   : %.0f +/- %.0f \n",nchexp,dnchexp);

	}
	//
	leg1->Draw("same");





}

//______________________________________________
TH1* GetNchFromFile(const char* filename )
{
	/**
	 * Read file and store values in vector
	 */
	 vector<double> x;
	 vector<double> y;
	 vector<double> yerr;

	 ifstream in(filename);
   char line[1024];

	 float a,b;
   float value,sys;

	 while (in.getline(line,1023,'\n'))
   {

     if (strstr(line, "//")) continue;
     sscanf(line,"%e-%e %e %e",&a,&b,&value,&sys);

		//  printf("%e-%e %e %e \n",a,b,value,sys);

     x.push_back(a);
     y.push_back(value);
     yerr.push_back(sys);


   }

	 x.push_back(b);

	 TH1* h = new TH1F(filename,filename,x.size()-1,&x[0]);

	 for ( Int_t i = 1; i <= h->GetXaxis()->GetNbins(); ++i )
	 {
		 h->SetBinContent(i,y[i-1]);
		 h->SetBinError(i,yerr[i-1]);
	 }

	 return h;

}

//______________________________________________
TH1* GetWeightedMeanHisto_cent(TH1* h1,TH1* h2,TH1* h3)
{
	/**
	 * Return weighted mean histo from the 3 arguments
	 */

	 TH1* h = (TH1*)h1->Clone();
	 h->Reset();

	 for ( Int_t i = 1; i <= h->GetXaxis()->GetNbins(); ++i )
	 {
		 double x1 = h1->GetBinContent(i);
		 double x2 = h2->GetBinContent(i);
		 double x3 = h3->GetBinContent(i);

		 double dx1 = h1->GetBinError(i);
		 double dx2 = h2->GetBinError(i);
		 double dx3 = h3->GetBinError(i);

		 if(dx1<1) dx1=1;
		 if(dx2<1) dx2=1;
		 if(dx3<1) dx3=1;

		 double dxinvsum_sq =  1./(dx1*dx1) + 1./(dx2*dx3) + 1./(dx3*dx3);

		//  double x  = (x1/dx1/dx1 + x2/dx2/dx2 + x3/dx3/dx3)/dxinvsum_sq ;
		//  double dx = sqrt(1/dxinvsum_sq);

		 double x   = (x1 + x2 + x3)/3. ;
		 double dx  = (dx1 + dx2 + dx3)/3. ;

		 h->SetBinContent(i,x);
		 h->SetBinError(i,dx);
	 }

	 return h;
}

//______________________________________________
TH1* ProjectWeightedMeanHisto_cent(int ybin,int nbin,TH1* h_cent[10])
{
	/**
	 * Turn histo versus cent into hisot versus Y
	 */

	 TH1F* h = new TH1F("h","h",nbin,&Centrality_bin[0]);

	 for ( Int_t i = 1; i <= h->GetXaxis()->GetNbins(); ++i )
	 {
		 double x 	= h_cent[i-1]->GetBinContent(ybin+1);
		 double dx = h_cent[i-1]->GetBinError(ybin+1);

		 h->SetBinContent(i,x);
		 h->SetBinError(i,dx);
	 }

	 double nch =0.;
	 double dnch =0.;

	//  if(nbin>4) nch = h->IntegralAndError(1,h->GetXaxis()->GetNbins(),dnch);
	 /*if(nbin>4)*/ nch = h->IntegralAndError(1,4,dnch);
	 if(nbin>4) printf(" --- Nch for %f < y < %f at 5.02 TeV in 0-30%% (TH1 integral) : \n",y[ybin],y[ybin+1]);
	 else       printf(" --- Nch for %f < y < %f at 2.76 TeV in 0-30%% (TH1 integral) : \n",y[ybin],y[ybin+1]);
	 /*if(nbin>4)*/ printf(" ---> integral   : %f +/- %f \n",nch,dnch);

	 return h;

}

//______________________________________________
void EvalNch(TH1* h_y276TeV[6])
{
	/**
	 * Fit the distributions and evaluate integraded nch 0-90%
	 */

	//  TF1 *fitfunctiononly[6];
	//  for (size_t i = 0; i < 6; i++) {
	// 	 fitfunctiononly[i] = new TF1("f1","[0]*exp(-x)",0, 110);
	// 	 fitfunctiononly[i]->SetParameter(0,1200);
	// 	 fitfunctiononly[i]->FixParameter(1,0);
	// 	 fitfunctiononly[i]->SetLineColor(1);
	// 	 fitfunctiononly[i]->SetLineWidth(1);
	// 	 fitfunctiononly[i]->SetLineStyle(1);
	//  }

	 TF1 *fitfunction[6];
	 for (size_t i = 0; i < 6; i++) {
		 fitfunction[i] = new TF1("f2", "[0]*exp(-[1]*x)",0, 110);
		 fitfunction[i]->SetLineColor(2);
		 fitfunction[i]->SetLineWidth(1);
		 fitfunction[i]->SetLineStyle(2);
	 }


	 new TCanvas();

	 for ( Int_t i = 0; i < 6; ++i )
	 {
		// h_y276TeV[i]->Fit(fitfunctiononly[i],"0QSER","",0,30);
		//
		// double nch_exponly 	=0.;
		// double dnch_exponly =0.;
		// nch_exponly 				= fitfunctiononly[i]->Integral(0.,90.);
		// dnch_exponly 				= fitfunctiononly[i]->IntegralError(0.,90.);

		h_y276TeV[i]->Fit(fitfunction[i],"0QSER","",0,30);

		double nchexp 	=0.;
		double dnchexp 	=0.;
		nchexp 					= fitfunction[i]->Integral(0,30);
		dnchexp 				= fitfunction[i]->IntegralError(0,30);

		if(i==0)h_y276TeV[i]->DrawCopy();
		else 		h_y276TeV[i]->DrawCopy("same");
		// fitfunctiononly[i]->DrawCopy("same");
		fitfunction[i]->DrawCopy("same");



		printf(" -------- Nch for %.2f < y < %.2f : \n",y[i],y[i+1]);
		// printf(" ---> exp only : %.0f +/- %.0f \n",nch_exponly,dnch_exponly);
		printf(" ---> exp   : %.0f +/- %.0f \n",nchexp,dnchexp);

	 }

}
